import type { Metadata } from "next";
import "../globals.css";
import { Providers } from "@/ui/components/themeProviders/Providers";
import { Nav } from "@/ui/components/Nav/Nav";
import { UserProvider } from "@/lib/context/UserContext";

export const metadata: Metadata = {
  title: "software",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`bg-light-primary dark:bg-dark-primary `}>
        <UserProvider>
          <Providers>
            <Nav />
            {children}
          </Providers>
        </UserProvider>
      </body>
    </html>
  );
}
