import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/ui/components/themeProviders/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`bg-light-primary dark:bg-dark-primary `}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
